# Generated by Django 6.0.2 on 2026-02-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngoprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='NGO must be verified by admin before accessing dashboard'),
        ),
    ]
