# Generated by Django 6.0.2 on 2026-02-14 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0001_initial'),
        ('ngos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='linked_ngo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='ngos.ngoprofile'),
        ),
    ]
