# Generated by Django 6.0.2 on 2026-02-14 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_initial'),
        ('ngos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='assigned_ngo',
            field=models.ForeignKey(blank=True, help_text='NGO handling this complaint', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to='ngos.ngoprofile'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_assigned',
            field=models.BooleanField(default=False, help_text='Whether complaint has been assigned to volunteers'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='volunteers_helping',
            field=models.ManyToManyField(blank=True, help_text='Volunteers helping with this complaint', related_name='helping_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='linked_ngo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='ngos.ngoprofile'),
        ),
        migrations.CreateModel(
            name='ComplaintHelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='PENDING', max_length=10)),
                ('message', models.TextField(blank=True, help_text='Message to volunteer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_requests', to='complaints.complaint')),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_requests', to='ngos.ngoprofile')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('complaint', 'volunteer')},
            },
        ),
    ]
