# Generated by Django 6.0.2 on 2026-02-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('MEMBERSHIP_REQUEST', 'Membership Request'), ('MEMBERSHIP_APPROVED', 'Membership Approved'), ('MEMBERSHIP_REJECTED', 'Membership Rejected'), ('COMPLAINT_ACCEPTED', 'Complaint Accepted'), ('COMPLAINT_REJECTED', 'Complaint Rejected'), ('TASK_ASSIGNED', 'Task Assigned'), ('TASK_ACCEPTED', 'Task Accepted'), ('TASK_DECLINED', 'Task Declined'), ('TASK_COMPLETED', 'Task Completed'), ('COMPLETION_CONFIRMED', 'Completion Confirmed'), ('PROOF_REJECTED', 'Proof Rejected')], max_length=25)),
                ('message', models.TextField()),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
